# Generated by Django 5.2.5 on 2025-08-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detaliu_registras', '0004_remove_uzklausa_kaina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kaina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='klientas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projektas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uzklausa',
            options={},
        ),
        migrations.RemoveField(
            model_name='detale',
            name='faktinis_kiekis_reme',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kabinimas_xyz',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kabinimo_tipas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_metinis',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_partijai',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='kiekis_reme',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='nuoroda_brezinio',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='pakavimas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='plotas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='ppap_dokumentai',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='projektas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='standartas',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='svoris',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='busena',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='detalė',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='fiksuotas_kiekis',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='kiekis_iki',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='kiekis_nuo',
        ),
        migrations.RemoveField(
            model_name='kaina',
            name='yra_fiksuota',
        ),
        migrations.AddField(
            model_name='detale',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='detales/'),
        ),
        migrations.AddField(
            model_name='kaina',
            name='detale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detaliu_registras.detale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaina',
            name='kaina_iki',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kaina',
            name='kaina_nuo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='danga',
            name='pavadinimas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detale',
            name='brezinio_nr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='detale',
            name='danga',
        ),
        migrations.AlterField(
            model_name='detale',
            name='nuoroda_pasiulymo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='detale',
            name='pastabos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='detale',
            name='pavadinimas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='kainos_matas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='kaina',
            name='suma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='klientas',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='klientas',
            name='telefonas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='pasiulymo_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='pavadinimas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='uzklausos_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='danga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detaliu_registras.danga'),
        ),
    ]
